### ISSUE TITLE
VICON_TRACKER_IP

### ISSUE THREAD

**Issue by gaolongsen** [steffensc/pyvicon-datatstream-module#1]
Hi Author,

Thanks for your contribution to this package! I have a question about using it. For the **VICON_TRACKER_IP**, because I'm currently using Vicon Tracker 3.8 on a Win10 PC, all set up and object tracking work well. Also, I'm using a Ubuntu laptop and install this package. Both PC connect to the same network. I check the Vicon system's IP is 192.168.10.1, and the Win PC's IP is 192.168.50.99. I try both IP but all shows that connect failed. Do you know how to setup proper **VICON_TRACKER_IP** on my Ubuntu PC? Thanks for your time!(PS: my ubuntu PC's IP is 192.168.1.32)

**Comment by steffensc** [comment]
Hi @gaolongsen,

glad to hear the installation of my package on your Ubuntu machine was successful! :)
Unfortunately I have no direct access to a Vicon system at the moment anymore. So the following points are just ideas / guessing.

- Make sure that the Vicon Tracker application is started (application window is opened).
- What is the subnet mask of your network? Are you able to ping to the Win10 PC (192.168.50.99) on which Vicon Tracker 3.8 is installed? Also try to ping from the Win10 PC to your machine (192.168.1.32) ;).

If you manage to connect to the Vicon Tracker, please let me know and post the solution :).

Cheers and good luck,
Steffen

**Comment by gaolongsen** [comment]
Hi Steffen,

Thanks for your reply! Here is the shotscreen I got from my Windows PC which installed Tracker 3.8 :
![image](https://github.com/steffensc/pyvicon-datatstream-module/assets/23102798/1a060c6d-bec5-4b92-80f6-190e0668adfd)
![image](https://github.com/steffensc/pyvicon-datatstream-module/assets/23102798/42f6b6d3-3fa0-4cd0-9404-b1cfa36b80b7)
![image](https://github.com/steffensc/pyvicon-datatstream-module/assets/23102798/2109e757-0f7f-414b-b46c-4ec3cd12db82)

 Here is the screen shot I got from my Ubuntu PC which has already install your package:

![image](https://github.com/steffensc/pyvicon-datatstream-module/assets/23102798/0510b232-660f-4c7d-aa6d-1fcc36be0c38)

I try to ping 192.168.1.32 from my Windows PC which installed Tracker 3.8, Here is the screen shot I got from my Windows PC
![image](https://github.com/steffensc/pyvicon-datatstream-module/assets/23102798/ca7b8d34-4e8e-462e-af50-de83160d3920)

**Comment by gaolongsen** [comment]
Hi Steffen,

We solved the problem! The reason why my Ubuntu PC cannot visit the Vicon PC is the issues for our lab's ethernet setup. I use the Wifi dongle for Vicon PC and now I can ping to Vicon PC from my Ubuntu PC and can get data from Tracker!! I also examine the data, it's so accurate and the package works perfectly!!! Thanks for your contribution for this and really appreciate your help!!

**Comment by steffensc** [comment]
Nice to hear that you could solve the problem :)
